use anyhow::Result;
use std::{fs, path::Path};

pub struct WorkspaceBootstrap;

impl WorkspaceBootstrap {
    pub fn exists() -> bool {
        Path::new("GALAXY.md").exists()
    }

    pub fn create_template() -> String {
        r#"# GALAXY.md

## Project

Unknown project.

## Languages

Not detected.

## Structure

Not inspected.

## Important Files

Not discovered.

## Notes

Generated by Luma.
"#
        .to_string()
    }

    pub fn initialize() -> Result<()> {
        if !Self::exists() {
            fs::write("GALAXY.md", Self::create_template())?;
        }

        Ok(())
    }

    pub fn load() -> Result<String> {
        Ok(fs::read_to_string("GALAXY.md")?)
    }

    pub fn regenerate() -> Result<()> {
        fs::write("GALAXY.md", Self::create_template())?;

        Ok(())
    }
}
