use anyhow::Result;
use std::path::Path;

use crate::tools::ToolRegistry;

pub struct WorkspaceBootstrap;

impl WorkspaceBootstrap {
    pub fn exists() -> bool {
        Path::new("GALAXY.md").exists()
    }

    pub fn create_template() -> String {
        r#"# GALAXY.md

## Project

Unknown project.

## Languages

Not detected.

## Structure

Not inspected.

## Important Files

Not discovered.

## Notes

Generated by Luma.
"#
        .to_string()
    }

    pub async fn initialize(tools: &ToolRegistry) -> Result<()> {
        if Self::exists() {
            return Ok(());
        }

        let content = Self::create_template();

        tools.execute(
            "write_file",
            &serde_json::json!({
                "path": "GALAXY.md",
                "content": content
            })
            .to_string(),
        )?;

        Ok(())
    }
}
